### ISSUE TITLE
IT-News-Feed

### ISSUE THREAD

**Issue by Magiranu** [odan/slim-csrf#2]
Hallo Herr Opitz,
ich schreibe Ihnen hier, weil ich keine E-Mail Adresse von Ihnen finde, über die ich Sie kontaktieren kann. Ich hatte mir zuvor einen Twitter-Account angelegt und ihnen eine Nachricht geschrieben. Doch leider wurde der Account tempörär gesperrt und ich muss ihn mittels SMS reaktivieren. Anders geht es nicht. Doch darauf habe ich keine Lust. Darum jetzt hier. Konnten Sie evtl. trotzdem meine Nachricht lesen und könnten Sie vielleicht hier antworten?
Freundliche Grüße

**Comment by odan** [comment]
Hallo @Magiranu 

Für Fragen stehe auch hier auf Github gerne zur Verfügung.

Freundliche Grüsse

**Comment by Magiranu** [comment]
Okay, scheinbar hat Twitter meine Nachricht gelöscht. Also ich hatte Sie gefragt, ob es möglich ist, dass Sie mir den Code zu ihrem Newsfeed geben könnten? Ich würde gerne auch so etwas bauen, bin dort aber nicht so versiert. Mein Ziel ist es, nicht nur gestern und heute anzuzeigen, sondern sieben Tage rückwirkend. In Ihren eigenen Repositories hier auf Github, finde ich es leider nicht. Ich meine diese Seite, falls Sie sich fragen wovon ich schreibe: http://www.opitz-online.com/feeds/

**Comment by odan** [comment]
Der Code ist noch prozedural und mittlerweile nicht mehr so top modern. Ich könnte das Projekt auf Github stellen wenn Sie möchten.

**Comment by Magiranu** [comment]
Es macht doch nichts, wenn er nicht mehr so modern ist. Das Ergebnis zählt doch, und ich finde es sehr gut. Die Seite steuere ich gar nicht mehr direkt an, ich habe nur noch Ihren Link zum Feed und benutze den. Viel Zeitsparender. Wenn Sie den Code hochladen würden, wäre das super.

**Comment by odan** [comment]
Ich habe den Quellcode hochgeladen. Hier kann man ihn jetzt finden: https://github.com/odan/news-feed
