### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AlexMcDee** [odan/slim-csrf#3]
Hello. Don't forget to change
`composer install odan/slim-csrf`
to
`composer require odan/slim-csrf`

and if I'm not mistaken
    `$sessionId = $session->getId();`
    `$csrf = new \App\Middleware\CsrfMiddleware($sessionId);`
to 
    `$sessionId = $session->getId();`
    `$csrf = new \Odan\Slim\Csrf\CsrfMiddleware($sessionId);`

Best regards, Alex.

**Comment by odan** [comment]
Yes, thanks @AlexMcDee. I fixed it.
