### ISSUE TITLE
Throw 403 Instead of of new RuntimeException

### ISSUE THREAD

**Issue by madsem** [odan/slim-csrf#4]
Hey, just installed this in favor of slimphp/slim-csrf that has issues with multiple dynamic forms (which this one hopefully doesn't).

Just wanted to ask if you think throwing a 403 might be more appropriate than a runtime exception?

**Comment by odan** [comment]
403 is a HTTP specific error code and not a PHP Exception like `RuntimeException`. But I know what you mean. The CSRF library could throw a specific e.g. `InvalidCsrfTokenException` and your (Slim) Exception Middleware could map it into a Response with a 403 HTTP-StatusCode.

**Comment by madsem** [comment]
That would be a better option yeah, agree :)

How would you handle WYSIWYG editors with this middleware?

This is the issue:

I'm using Froala, when you add/remove images a post request is made, but since the Froala editor is part of a bigger html form, this form generates a RunTimeException on submit, because of the previous http post request(s) made by the editor.

Is there a good way to handle these scenarios?

Thanks for your hard work man, appreciated :)

**Comment by odan** [comment]
In Froala it's possible to add the CSRF-token via the `imageUploadParams` option:

https://www.froala.com/wysiwyg-editor/docs/options#imageUploadParams

```js
.on('editable.beforeImageUpload', function (e, editor, images) {
    editor.options.imageUploadParams[csrf_token_name]=csrf_token_value;        
})
```

Source: https://github.com/froala/wysiwyg-editor/issues/571#issuecomment-109294137

**Comment by madsem** [comment]
Yeah that is not the issue, I did that already.
The problem is that after every POST request a new csrf token is generated, and simply dropping/adding a new image in Froala (or other editors) already generates a POST request to save images/files.

And when you then submit the html form you get a runtime exception...

So the first request works, but subsequent request do not because the token changed and the html still has the old token everywhere.

**Comment by odan** [comment]
Well the Token depends on the session id. This would mean, that your session id changes after every request?

**Comment by madsem** [comment]
I'm using redis sessions, in this format:
```text
klever_b678cad862317ece8cc1041bf8a16ce928896f23da66e7f1e30a79d33afd62cbaab1b2727dbba23b
```

**Comment by madsem** [comment]
Okay, it actually started working, sorry lol :)
Def. not a problem of your middleware.

I think there must have been some kind of cache from slimphp/slim-csrf that caused this, because that package doesn't work correct with multiple forms.

For anyone who runs into this, use this to add the csrf token to the headers that Froala sends:
```js
requestHeaders: {
               "X-CSRF-Token":  '{{ csrf_token }}',
            },
```
