### ISSUE TITLE
GET Forms Stop Automated Protection

### ISSUE THREAD

**Issue by madsem** [odan/slim-csrf#5]
How can I selectively stop CSRF tokens from being added to GET forms only?
As CSRF protection is really only needed for POST forms, and I would like to get rid of the __token parameter in my search urls :)

Thanks for the great job!

**Comment by odan** [comment]
Just update to the latest version (>=1.1.0) and disable the protection for GET forms like this:

```php
$csrf->protectForms(true, false);
```

**Comment by madsem** [comment]
Thanks man! That was quick, really appreciate that.
